// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // Sidebar: [
  //   'introduction',
  //   {
  //     type: 'category',
  //     label: '🥚 Ranch Expansion',
  //     items: ['ranch-expansion/description','ranch-expansion/content','ranch-expansion/installation','ranch-expansion/compatibility','ranch-expansion/changelog'],
  //   },
  //   {
  //     type: 'category',
  //     label: '🔪 Melee Expansion',
  //     items: ['melee-expansion/description','melee-expansion/content','melee-expansion/installation','melee-expansion/compatibility','melee-expansion/changelog'],
  //   },
  //   {
  //     type: 'category',
  //     label: '🔨 Tool Expansion',
  //     items: ['tool-expansion/description','tool-expansion/content','tool-expansion/installation','tool-expansion/compatibility','tool-expansion/changelog'],
  //   },
  // ],
};

export default sidebars;
